 // m=i/2;
        // for(j=2;j<=m;j++)
        // {
        //     if(i%j==0)
        //     {
        //         flag=1;
        //         break;
        //     }
        // }
        // if(i=1)
        //     printf("");
        // if(flag=0)